greenhouse_companies:
  - notion
  - stripe
  - figma
  - airbnb
  - datadog
  - asana

keywords:
  - data engineer
  - analytics
  - migration
  - automation
  - ETL
  - python

filter:
  days_old_max: 7
  dedup_fields: ["title", "location.name"]
  required_keywords: ["data", "engineer"]
  score_boost_keywords: ["remote", "python", "etl", "sql"]
