# config/config.yaml
general:
  top_n_jobs: 5
  days_old_max: 1
  use_gpt: false

filter:
  required_keywords:
    - data
    - engineer
    - analytics
    - migration
    - automation
  score_boost_keywords:
    - remote
    - python
    - etl

user_profile:
  name: "Brandon Crow"
  email: "brandoncrow87@gmail.com"
  phone: "(405) 408-5892"

templates:
  data engineer: "data_engineer.txt"
  analytics engineer: "analytics_engineer.txt"
  integration: "integration.txt"
  quality: "data_quality_engineer.txt"
  etl: "etl_developer.txt"
  default: "data_engineer.txt"

scrapers:
  greenhouse:
    companies:
      - notion
      - stripe
      - figma
      - airbnb
      - datadog
      - asana

model:
  name: gpt-4o
  temperature: 0.5

email:
  mode: smtp
  smtp_server: smtp.gmail.com
  smtp_port: 587
  from_address: brandoncrow87@gmail.com
  to_address: brandoncrow87@gmail.com
  subject_prefix: "Your Daily Job Matches"